void Error(int i,char *s);
void GETCHAR();
int isreserved(char s[]);
rebound lex();
bool istype(int t);
bool isfirsts(int t);
bool isfirste(int t);
void ignorance(int i);
void READ();
void copystruct(rebound &a,rebound &b);

void Program();
void Constdec();
void Constdef();
void Vardec();
void Vardef();
void Funcdef();
bool Dechead(int &t,char n[]);
void Procdef();
void Mainproc();
void Comsentence();
void Sentencelist();
void Sentence();
void Assignsent();
void Ifsent();
void Condition();
void Loopsent();
void Funccall();
void Proccall();
void Readsent();
void Writesent();
void Returnsent();
void Expression(int &t);
void Term(int &t);
void Factor(int &t);
void Parameter(int j,int &k);
void Paratable(int j,int &k);
void Paralist(int i,int z);
void Integer(int &s,int &c);
void Float(int &s,float &c);
void Char(int &s,char &c);
void Print(char p[]);
void Print(char p[],int i);
void Print(char p[],int i,int j);
void Print(char p[],float f);
void Print(char p[],char s[]);
void tableinsert(char n[],int t,int kind);
bool Isintable(char n[]);
int Lookup(char n[],int &l,int &j);
int Lookup(char n[]);
bool Lookuproc(char n[],int &i,int &z);
bool Lookuproc(char n[],int &type);
void LOAD(int c);
void LOAD(float c);
void LOAD(char c);
void STO(int t,int s,int l,int j);
void Labelproduce(char lab[]);
void Labelinsert(char s[]);
void allocspace(int k);
void QuitTable();
void Type(int l,int j,int &t1);
void conjump(int t1,int t2,int t);
void Write(int t);
void Opr(int &s1,int s2,int tp);
void Upcnt(int j,int &k);
bool Chktype(int t,int i,int &m,int &z);
bool ChkLength(int z);

int Locate(char s[]);
int LocLabel(char s[]);
int getAdd(int &ll,int &on,char s[]);
int Cal(int t);
int GetData(float f[],int t[],int &type);
void Interpreter(char *fileName);
void maininitial();